name: Bug Report
description: Create a report to help us improve
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting!

        Could you please provide the following information? It helps me help you faster.

        You can copy-paste some of the required information here by typing `/itemversion issue` in the in-game chat window

  - type: checkboxes
    id: flavor
    attributes:
      label: In which flavor are you encountering the bug?
    options:
      - label: Vanilla
      - label: Classic
      - label: Retail
    validations:
      required: true

  - type: dropdown
    id: using_latest
    attributes:
      label: Are you using the latest version of ItemVersion?
      description: "Compare the output of `/itemversion issue` to the latest release on GitHub or Curseforge. Upgrade to the latest version that you can."
    options:
      - label: "No"
      - label: "Yes"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug, what should happen instead, and **how to reproduce it**.
    validations:
      required: true

