name: Item with wrong version
description: Fix an item's version
labels: [item fix]

body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting!

        Could you please provide the following information? It helps me help you faster.

        You can copy-paste some of the required information here by typing `/itemversion issue` in the in-game chat window

  - type: checkboxes
    id: flavor
    attributes:
      label: In which flavor are you seeing the wrong version?
      options:
        - label: Vanilla
        - label: Classic
        - label: Retail
    validations:
      required: true

  - type: dropdown
    id: using_latest
    attributes:
      label: Are you using the latest version of ItemVersion?
      description: "Compare the output of `/itemversion issue` to the latest release on GitHub or Curseforge. Upgrade to the latest version that you can."
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: textarea
    id: wowhead_url
    attributes:
      label: Wowhead URL(s) for item.
    validations:
      required: true

  - type: input
    id: where
    attributes:
      label: How are you encountering this item? Is it in your bags? A chat link? Some other part of the UI?
    validations:
      required: true

  - type: textarea
    id: correction
    attributes:
      label: What should this item's expansion/version be instead, and **why**?
    validations:
      required: true